title: Steven Sio
logo: /assets/img/headshot_circle.jpg
description: "LinkedIn: <a href='https://www.linkedin.com/in/steven-sio/' target='_blank'>linkedin.com/in/steven-sio</a><br>Email: <a href='mailto:stevenscw3253@gmail.com'>stevenscw3253@gmail.com</a><br>WhatsApp: +853 62296661"
show_downloads: false
theme: jekyll-theme-minimal
